package org.example.test;

public class SchemaConstants {
    public static final String SCHEMA_BASIC = "{\n"
            + "   \"type\" : \"record\",\n"
            + "   \"namespace\" : \"Tutorialspoint\",\n"
            + "   \"name\" : \"Employee\",\n"
            + "   \"fields\" : [\n"
            + "      { \"name\" : \"Name\" , \"type\" : \"string\" },\n"
            + "      { \"name\" : \"Age\" , \"type\" : \"int\" }\n"
            + "   ]\n"
            + "}";
    public static final String SCHEMA_ENUM = "{\n"
            + "    \"type\": \"record\",\n"
            + "    \"name\": \"Test\",\n"
            + "    \"namespace\": \"com.acme\",\n"
            + "    \"fields\": [{\n"
            + "            \"name\": \"name\",\n"
            + "            \"type\": \"string\"\n"
            + "        }, {\n"
            + "            \"name\": \"age\",\n"
            + "            \"type\": \"int\"\n"
            + "        }, {\n"
            + "            \"name\": \"sex\",\n"
            + "            \"type\": \"string\"\n"
            + "        }, {\n"
            + "            \"name\": \"myenum\",\n"
            + "            \"type\": [\"null\", {\n"
            + "                    \"type\": \"enum\",\n"
            + "                    \"name\": \"Suit\",\n"
            + "                    \"symbols\": [\"SPADES\", \"HEARTS\", \"DIAMONDS\", \"CLUBS\"]\n"
            + "                }\n"
            + "            ]\n"
            + "        }\n"
            + "    ]\n"
            + "}";

    public static final String SCHEMA_ARRAY = "{\n"
            + "    \"name\": \"Parent\",\n"
            + "    \"type\":\"record\",\n"
            + "    \"fields\":[\n"
            + "        {\n"
            + "            \"name\":\"children\",\n"
            + "            \"type\":{\n"
            + "                \"type\": \"array\",  \n"
            + "                \"items\":{\n"
            + "                    \"name\":\"Child\",\n"
            + "                    \"type\":\"record\",\n"
            + "                    \"fields\":[\n"
            + "                        {\"name\":\"name\", \"type\":\"string\"}\n"
            + "                    ]\n"
            + "                }\n"
            + "            }\n"
            + "        }\n"
            + "    ] \n"
            + "}";

    public static final String SCHEMA_UNION_NULL_FIRST = "{ \n"
            + "   \"type\" : \"record\", \n"
            + "   \"namespace\" : \"tutorialspoint\", \n"
            + "   \"name\" : \"empdetails\", \n"
            + "   \"fields\" : \n"
            + "   [ \n"
            + "      { \"name\" : \"experience\", \"type\": [\"int\", \"null\"] }, { \"name\" : \"age\", \"type\": \"int\" } \n"
            + "   ] \n"
            + "}";

    public static final String SCHEMA_UNION = "{ \n"
            + "   \"type\" : \"record\", \n"
            + "   \"namespace\" : \"tutorialspoint\", \n"
            + "   \"name\" : \"empdetails\", \n"
            + "   \"fields\" : \n"
            + "   [ \n"
            + "      { \"name\" : \"experience\", \"type\": [\"int\", \"null\"] }, { \"name\" : \"age\", \"type\": \"int\" } \n"
            + "   ] \n"
            + "}";
}
